import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Menu, X, ChevronDown } from 'lucide-react';
import './styles.css';

const treatments = [
  ['Smile Makeover', 'A complete composition of form, tone and proportion — designed around you.', 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=900&q=85'],
  ['Porcelain Veneers', 'Fine porcelain, quietly transformative, made to catch light like natural enamel.', 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=900&q=85'],
  ['Invisalign®', 'A discreet route to balance, guided with exacting digital precision.', 'https://images.unsplash.com/photo-1571772996211-2a78c5a6d6b6?auto=format&fit=crop&w=900&q=85'],
  ['Teeth Whitening', 'A refined brightening ritual for a smile with unmistakable freshness.', 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=900&q=85'],
  ['Dental Implants', 'A considered restoration of strength, comfort and natural confidence.', 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=900&q=85'],
  ['Full Mouth Reconstruction', 'A deeply personal return to ease, function and beauty.', 'https://images.unsplash.com/photo-1606265752439-1f18756aa2f2?auto=format&fit=crop&w=900&q=85']
];
const doctors = [
  ['Dr. Amara Hayes', 'Founder · Aesthetic Dentistry', 'Trained at the London Institute of Esthetic Dentistry · 16 years in smile design', 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=700&q=85'],
  ['Dr. Julian Reed', 'Prosthodontist', 'Trained at the Royal College of Surgeons · 14 years in restorative artistry', 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=700&q=85'],
  ['Dr. Nia Laurent', 'Orthodontic Specialist', 'Trained at Institut Dentaire Paris · 12 years in discreet alignment', 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=700&q=85']
];
function App(){
 const [open,setOpen]=useState(false), [scrolled,setScrolled]=useState(false), [sent,setSent]=useState(false);
 useEffect(()=>{ const h=()=>setScrolled(scrollY>40); addEventListener('scroll',h); return()=>removeEventListener('scroll',h)},[]);
 const links=['Treatments','Philosophy','Specialists','Results','Contact'];
 return <>
  <header className={`nav ${scrolled?'nav-solid':''}`}><a href="#home" className="wordmark">LUMIÈRE <span>Dental Studio</span></a><nav>{links.map(x=><a href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a href="#book" className="nav-cta">Book consultation <ArrowUpRight size={15}/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header>
  <div className={`mobile-nav ${open?'show':''}`}>{links.map(x=><a onClick={()=>setOpen(false)} href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}<a href="#book" onClick={()=>setOpen(false)}>Book consultation</a></div>
  <main>
   <section id="home" className="hero"><img src="/images/lumiere-hero.png" alt="Woman smiling in a luxury dental studio"/><div className="hero-shade"/><div className="hero-copy reveal"><p className="eyebrow light">Aesthetic dentistry, considered</p><h1>Confidence,<br/><i>illuminated.</i></h1><p className="hero-text">Where clinical precision meets the quiet art of a beautiful smile.</p><a className="btn btn-light" href="#book">Begin your consultation <ArrowUpRight size={16}/></a></div><div className="hero-bottom">NEW DELHI · EST. 2012 <span>SCROLL TO DISCOVER ↓</span></div></section>
   <section id="treatments" className="section treatments"><div className="section-intro"><p className="eyebrow">The signature collection</p><h2>Exceptional care,<br/><i>beautifully personal.</i></h2><p>Our most sought-after treatments are thoughtful studies in confidence — composed with restraint, balance and lasting intention.</p></div><div className="treatment-grid">{treatments.map(([name,copy,img],i)=><article className={`treatment treatment-${i}`} key={name}><img src={img} alt=""/><div className="treatment-overlay"><span>0{i+1}</span><h3>{name}</h3><p>{copy}</p><a href="#book" aria-label={`Explore ${name}`}><ArrowUpRight size={19}/></a></div></article>)}</div></section>
   <section id="philosophy" className="split-section"><div className="split-image"><img src="https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=1200&q=85" alt="Calm minimal studio interior"/></div><div className="split-copy"><p className="eyebrow">Our philosophy</p><h2>The rare luxury<br/>of <i>being understood.</i></h2><div className="rule"/><p>Every smile has its own architecture. We begin by listening — to your features, your ambitions, the way you want to feel when you enter a room. Then we bring together advanced dentistry and an artist’s eye to create something that belongs only to you.</p><a href="#book" className="text-link">Discover our approach <ArrowUpRight size={16}/></a></div></section>
   <section id="specialists" className="section specialists"><div className="centered"><p className="eyebrow">The Lumière collective</p><h2>Masters of the<br/><i>subtle difference.</i></h2></div><div className="doctor-grid">{doctors.map(([name,role,cred,img])=><article className="doctor" key={name}><div className="doctor-img"><img src={img} alt={name}/></div><p className="eyebrow">{role}</p><h3>{name}</h3><p className="credential">{cred}</p></article>)}</div></section>
   <section id="results" className="results"><div className="results-heading"><p className="eyebrow light">Artistry, revealed</p><h2>Not a new smile.<br/><i>Your smile, fully realised.</i></h2></div><div className="before-after"><div><img src="https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?auto=format&fit=crop&w=1200&q=85" alt="Before smile transformation"/><span>Before</span></div><div><img src="https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&w=1200&q=85" alt="After smile transformation"/><span>After</span></div></div><p className="results-note">Results vary for every individual. Your story starts with a conversation.</p></section>
   <section className="quotes"><p className="eyebrow">In their words</p><blockquote>“The experience felt less like an appointment and more like being cared for by people who understand beauty.”</blockquote><p className="attribution">MAYA S. · SMILE MAKEOVER PATIENT</p><div className="quote-nav"><button>←</button><span>01 / 03</span><button>→</button></div></section>
   <section id="book" className="booking"><div><p className="eyebrow light">A first conversation</p><h2>Your next chapter<br/>begins <i>quietly.</i></h2><p>Share a few details and our concierge will arrange a private consultation at your preferred pace.</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><span>✦</span><h3>We look forward to meeting you.</h3><p>Our concierge will be in touch shortly.</p></div>:<><label>Name<input required placeholder="Your full name"/></label><div className="form-row"><label>Phone<input required placeholder="+91 00000 00000"/></label><label>Email<input type="email" required placeholder="you@email.com"/></label></div><label>Preferred treatment<select defaultValue=""><option value="" disabled>Select an option</option>{treatments.map(x=><option key={x[0]}>{x[0]}</option>)}</select><ChevronDown size={16}/></label><label>Message<textarea placeholder="Tell us a little about your vision" rows="3"/></label><button className="btn btn-light">Request consultation <ArrowUpRight size={16}/></button></>}</form></section>
   <section id="contact" className="contact"><div><p className="eyebrow">Visit Lumière</p><h2>A little pause<br/>in the heart of <i>the city.</i></h2></div><div className="contact-info"><p><b>Studio</b>4th Floor, The Crescent<br/>Mehrauli, New Delhi 110030</p><p><b>Inquiries</b>+91 11 4820 1888<br/>hello@lumieredental.example</p><p><b>Hours</b>Tuesday — Saturday, 9am — 6pm<br/>By private appointment</p></div><div className="map-placeholder"><span>LUMIÈRE</span><i>NEW DELHI</i><div className="pin">✦</div></div></section>
  </main><footer><a href="#home" className="wordmark">LUMIÈRE <span>Dental Studio</span></a><p>© 2026 Lumière Dental Studio. All rights reserved.</p><div><a href="#">Instagram</a><a href="#">Facebook</a></div></footer>
 </>
}
createRoot(document.getElementById('root')).render(<App/>);
